### ISSUE TITLE
Invalid app ID

### ISSUE THREAD

**Issue by j3k0** [nodrock/ANE-Facebook#3]
Getting better, it's now starting with AIR 18. I can open the facebook login dialog... however it fails:

```
Invalid App ID: fb123456789
```

Checked the Key Hashes (in case that could be related), seems good... Could it be possible the Facebook App doesn't like this "fb" in front of the ID?

**Comment by j3k0** [comment]
Worked, I believed this ANE expected FACEBOOK_APP_ID to have a "fb" prefix everywhere. Wrong

```
-                               fb.init("fb" + FACEBOOK_APP_ID);
+                               fb.init(FACEBOOK_APP_ID);
```

**Comment by nodrock** [comment]
Yeah I tried to explain it in note. Should I add there more informations or you think it is enough now?

NOTE: It is important to prefix YOUR_FB_APP_ID with "fb" in <meta-data> (and ONLY in <meta-data>) tag, because of bug in Android manifest file (http://stackoverflow.com/questions/16156856/android-facebook-applicationid-cannot-be-null). Facebook SDK code in this ANE was modified to recognize FB_APP_ID prefixed with "fb".
